import Head from "next/head";
import Header from "@/sections/Header";
import Footer from "@/sections/Footer";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Deardo Satria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-white px-10 md:px-20 dark:bg-zinc-900">
        {Header("Hello World!", "")}
        {children}
        <Footer />
      </div>
    </>
  );
};
export default Layout;
